### ISSUE TITLE
Port the extension to Firefox

### ISSUE THREAD

**Issue by nekoxuee** [Miguel2597/twitch-clip-vod-sync#2]
Since the extension is compatible with Firefox it shouldn't require any changes.

**Comment by RandyJackson59** [comment]
Yes please, i would love to have this on Firefox too

**Comment by Miguel2597** [comment]
Submitted, waiting for approval.

**Comment by Miguel2597** [comment]
It is now available on Firefox: https://addons.mozilla.org/en-US/firefox/addon/twitch-clip-vod-sync
